### ISSUE TITLE
Cannot invite editor to workspace

### ISSUE THREAD

**Issue by 0xk2** [hectagon-finance/syncvote#106]
https://www.notion.so/hectagondao/e9f38d0bb5f74c6d82aba0bb93c92a25?pvs=4

**Comment by trungbaotran1701** [comment]
- Đọc docs luồng invite email supabase để check password genarate ra là gì ?
- Thiết kế màn thay password (là màn dẫn link email). 
- Đọc xem token invite lúc nhận email làm gì ?
