### ISSUE TITLE
Cannot invite editor to workflow

### ISSUE THREAD

**Issue by 0xk2** [hectagon-finance/syncvote#107]

**Comment by onspeedhp** [comment]
(
  auth.uid() IN 
  (
    SELECT user_org.user_id
    FROM user_org, workflow_version, workflow
    WHERE 
    (
      user_org.org_id IN 
      (
        SELECT workflow.owner_org_id
        FROM workflow
        WHERE 
        (
          workflow.id = workflow_version.workflow_id
        )
      )
    )
  )
)
OR
(
  auth.uid() IN 
  (
    SELECT workflow_version_editor.user_id
    FROM workflow_version_editor, workflow_version, workflow
    WHERE 
    (
      workflow_version_editor.workflow_version_id = workflow_version.id AND
      workflow_version.workflow_id = workflow.id
    )
  )
)

**Comment by onspeedhp** [comment]
> ( auth.uid() IN ( SELECT user_org.user_id FROM user_org, workflow_version, workflow WHERE ( user_org.org_id IN ( SELECT workflow.owner_org_id FROM workflow WHERE ( workflow.id = workflow_version.workflow_id ) ) ) ) ) OR ( auth.uid() IN ( SELECT workflow_version_editor.user_id FROM workflow_version_editor, workflow_version, workflow WHERE ( workflow_version_editor.workflow_version_id = workflow_version.id AND workflow_version.workflow_id = workflow.id ) ) )

Idk st wrong with this policies but new editor cannot edit
