### ISSUE TITLE
Create new Header for WorkflowVersion & Mission Editor Page

### ISSUE THREAD

**Issue by 0xk2** [hectagon-finance/syncvote#23]
location: `/layout/fragments/EditorHeader`

![Screenshot 2023-06-27 at 15 11 55](https://github.com/hectagon-finance/syncvote/assets/13373593/18a8d72d-4558-42c6-ada1-982413410c83)

**Comment by trungbaotran1701** [comment]
First join page can't see Saved!, after change have button Save, after click => Saved! 
Click publish: Show modal (insert value in the workflow version table: click Yes =>  Public Community, click No => UnPublic Community)
