### ISSUE TITLE
Change UI of HomePage

### ISSUE THREAD

**Issue by 0xk2** [hectagon-finance/syncvote#25]
![Screenshot 2023-06-27 at 15 53 09](https://github.com/hectagon-finance/syncvote/assets/13373593/38e78876-b384-45f3-b85a-a46d217a8c0b)
Can go back to either Shared or Own spaces

**Comment by trungbaotran1701** [comment]
Home: All oranization published
My spaces: organization of owner
Shared spaces: shared organization

**Comment by 0xk2** [comment]
note: do not include context panel
