### ISSUE TITLE
Build public view

### ISSUE THREAD

**Issue by 0xk2** [hectagon-finance/syncvote#6]
Public view require a different layout:
- A new header component
- A left-size drawer
- Public link without login
- Mobile support

Link to design: https://www.figma.com/file/awcERTKfeARChLH4lmFauP/Syncvote-UI-UX?type=design&node-id=26%3A22936&mode=design&t=c5idRKR3s6qxkDYn-1

Note: build a new layout

**Comment by onspeedhp** [comment]
- Change session to redux user.

**Comment by onspeedhp** [comment]
Move items to jsx code to use reactjs dom cache

**Comment by onspeedhp** [comment]
Change image to banner_url => tạo 1 component để hiển thị banner
